language: php

php:
  - 5.6
  - 7.2
  - 7.3

env:
  matrix:
    - TYPO3_VERSION="^7.6"
    - TYPO3_VERSION="^8.7"
    - TYPO3_VERSION="^9.5"

matrix:
  exclude:
    - php: 5.6
      env: TYPO3_VERSION="^8.7"
    - php: 5.6
      env: TYPO3_VERSION="^9.5"

sudo: false

notifications:
  email:
    recipients:
      - info@creativeworkspace.de
    on_success: always
    on_failure: always

addons:
  apt:
    packages:
      - parallel

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer self-update

before_script:
  - composer require typo3/cms="$TYPO3_VERSION"
  # Restore composer.json
  - git checkout composer.json
  - export TYPO3_PATH_WEB=$PWD/.Build

script:
  - >
    echo;
    echo "Running php lint";
    find . -name \*.php ! -path "./.Build/*" | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;

  - >
    echo;
    echo "Running unit tests";
    .Build/vendor/bin/phpunit -c .Build/vendor/nimut/testing-framework/res/Configuration/UnitTests.xml Tests/Unit/

  - >
    echo;
    export typo3DatabaseName="typo3";
    export typo3DatabaseHost="localhost";
    export typo3DatabaseUsername="root";
    export typo3DatabasePassword="";
    find 'Tests/Functional' -wholename '*Test.php' | parallel --gnu 'echo; echo "Running functional test suite {}"; .Build/vendor/bin/phpunit --colors  -c .Build/vendor/nimut/testing-framework/res/Configuration/UnitTests.xml {}'
